PATCH http://localhost:8080/quizrooms/1/join
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDc3MDA2NjAsInVzZXJfaWQiOjIsInVzZXJuYW1lIjoidGVzdDIifQ.MNkNMGbXAHYAEyKjwzWgOkyzRYWoHlPgO7z9JvhQWQU