PATCH http://localhost:8080/quizrooms/1/join
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDc3NDEwOTksInVzZXJfaWQiOjIsInVzZXJuYW1lIjoidGVzdDIifQ.lsyO5394atTuNn_H-dfnrT0krcRX1JcyWgt0roBZdIQ