POST http://localhost:8080/create-quizroom
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDc2OTU3ODUsInVzZXJfaWQiOjEsInVzZXJuYW1lIjoidGVzdCJ9.-3uL-wqRbMm5nfuOg6OyayFxnlCQdYuOoagp0otn2VI
  
  {
  "Players": [
    {
      "PlayerId": 1,
      "Username": "test"
    }
  ],
  "TimerTime": 60,
  "QuizTopic": "Science"
}
