POST http://localhost:8080/create-quizroom
Content-Type: application/json

{
  "Players": [
    {
      "PlayerId": 101,
      "Username": "Yashik"
    }
  ],
  "TimerTime": 60,
  "QuizTopic": "Science"
}
