POST http://localhost:8080/create-quizroom
Content-Type: application/json

{
  "Players": [
    {
      "PlayerId": 101,
      "Username": "shree Ram"
    }
  ],
  "TimerTime": 60,
  "QuizTopic": "Science",
  "ScoreSheet": {
    "101": 0
  }
}
