POST http://localhost:8080/create-quizroom
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDc5MjUzNDAsInVzZXJfaWQiOjEsInVzZXJuYW1lIjoidGVzdCJ9.-v3lUx50t0SpntamoJm0QchS6ZEQEdFRYd99aVMEW9k
  
  {
  "Players": [
    {
      "PlayerId": 1,
      "Username": "test"
    }
  ],
  "TimerTime": 60,
  "QuizTopic": "Science"
}
