POST http://localhost:8080/create-quizroom
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDgyMDQzMTIsInVzZXJfaWQiOjIsInVzZXJuYW1lIjoidGVzdDIifQ.nWaKU360cRrtHiIhYwh2u0CHX1Pdt0OzgtQroOCrPRw  
  
  {
  "Players": [
    {
      "PlayerId": 2,
      "Username": "test2"
    }
  ],
  "TimerTime": 60,
  "QuizTopic": "Science"
}
